name: Hello World Workflow

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main

# Define the job
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    
    steps:
      # Print "Hello World!"
      - name: Say Hello World
        run: echo "Hello World!"
